// Generated by CoffeeScript 1.6.3
(function() {
  var auth, serializer;

  require("./module_setup");

  auth = {};

  DS.Model.reopenClass({
    loadMore: function() {
      var page;
      page = DS.defaultStore.typeMapFor(this).metadata.page + 1;
      return this.find({
        page: page
      });
    }
  });

  Em.ArrayController.reopen({
    modelClass: function() {
      return this.get('firstObject').constructor;
    },
    showMore: function() {
      return this.modelClass().loadMore();
    }
  });

  serializer = DS.RESTSerializer.create();

  Em.PaginationAdapter = DS.RESTAdapter.reopen({
    serializer: serializer
  });

  serializer.configure({
    total: 'total',
    last_dt: 'last_dt',
    total_pages: 'total_pages',
    page: 'page'
  });

  module.exports = auth;

}).call(this);
